// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
const __dirname = import.meta.dirname;

dotenv.config({ path: `${__dirname}/../.env` });
import { defineConfig } from "prisma/config";

const databaseUrl = "postgresql://postgres:1234@localhost:5432/shorty?schema=public"
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set.");
}

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
